// Generated by Molecule 0.7.3

use molecule::prelude::*;

use super::basic::*;
use super::cell::*;
#[derive(Clone)]
pub struct AccountCellDataV3(molecule::bytes::Bytes);
impl ::core::fmt::LowerHex for AccountCellDataV3 {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        use molecule::hex_string;
        if f.alternate() {
            write!(f, "0x")?;
        }
        write!(f, "{}", hex_string(self.as_slice()))
    }
}
impl ::core::fmt::Debug for AccountCellDataV3 {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        write!(f, "{}({:#x})", Self::NAME, self)
    }
}
impl ::core::fmt::Display for AccountCellDataV3 {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        write!(f, "{} {{ ", Self::NAME)?;
        write!(f, "{}: {}", "id", self.id())?;
        write!(f, ", {}: {}", "account", self.account())?;
        write!(f, ", {}: {}", "registered_at", self.registered_at())?;
        write!(
            f,
            ", {}: {}",
            "last_transfer_account_at",
            self.last_transfer_account_at()
        )?;
        write!(f, ", {}: {}", "last_edit_manager_at", self.last_edit_manager_at())?;
        write!(f, ", {}: {}", "last_edit_records_at", self.last_edit_records_at())?;
        write!(f, ", {}: {}", "status", self.status())?;
        write!(f, ", {}: {}", "records", self.records())?;
        write!(f, ", {}: {}", "enable_sub_account", self.enable_sub_account())?;
        write!(f, ", {}: {}", "renew_sub_account_price", self.renew_sub_account_price())?;
        let extra_count = self.count_extra_fields();
        if extra_count != 0 {
            write!(f, ", .. ({} fields)", extra_count)?;
        }
        write!(f, " }}")
    }
}
impl ::core::default::Default for AccountCellDataV3 {
    fn default() -> Self {
        let v: Vec<u8> = vec![
            114, 0, 0, 0, 44, 0, 0, 0, 64, 0, 0, 0, 68, 0, 0, 0, 76, 0, 0, 0, 84, 0, 0, 0, 92, 0, 0, 0, 100, 0, 0, 0,
            101, 0, 0, 0, 105, 0, 0, 0, 106, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        ];
        AccountCellDataV3::new_unchecked(v.into())
    }
}
impl AccountCellDataV3 {
    pub const FIELD_COUNT: usize = 10;
    pub fn total_size(&self) -> usize {
        molecule::unpack_number(self.as_slice()) as usize
    }
    pub fn field_count(&self) -> usize {
        if self.total_size() == molecule::NUMBER_SIZE {
            0
        } else {
            (molecule::unpack_number(&self.as_slice()[molecule::NUMBER_SIZE..]) as usize / 4) - 1
        }
    }
    pub fn count_extra_fields(&self) -> usize {
        self.field_count() - Self::FIELD_COUNT
    }
    pub fn has_extra_fields(&self) -> bool {
        Self::FIELD_COUNT != self.field_count()
    }
    pub fn id(&self) -> AccountId {
        let slice = self.as_slice();
        let start = molecule::unpack_number(&slice[4..]) as usize;
        let end = molecule::unpack_number(&slice[8..]) as usize;
        AccountId::new_unchecked(self.0.slice(start..end))
    }
    pub fn account(&self) -> AccountChars {
        let slice = self.as_slice();
        let start = molecule::unpack_number(&slice[8..]) as usize;
        let end = molecule::unpack_number(&slice[12..]) as usize;
        AccountChars::new_unchecked(self.0.slice(start..end))
    }
    pub fn registered_at(&self) -> Uint64 {
        let slice = self.as_slice();
        let start = molecule::unpack_number(&slice[12..]) as usize;
        let end = molecule::unpack_number(&slice[16..]) as usize;
        Uint64::new_unchecked(self.0.slice(start..end))
    }
    pub fn last_transfer_account_at(&self) -> Uint64 {
        let slice = self.as_slice();
        let start = molecule::unpack_number(&slice[16..]) as usize;
        let end = molecule::unpack_number(&slice[20..]) as usize;
        Uint64::new_unchecked(self.0.slice(start..end))
    }
    pub fn last_edit_manager_at(&self) -> Uint64 {
        let slice = self.as_slice();
        let start = molecule::unpack_number(&slice[20..]) as usize;
        let end = molecule::unpack_number(&slice[24..]) as usize;
        Uint64::new_unchecked(self.0.slice(start..end))
    }
    pub fn last_edit_records_at(&self) -> Uint64 {
        let slice = self.as_slice();
        let start = molecule::unpack_number(&slice[24..]) as usize;
        let end = molecule::unpack_number(&slice[28..]) as usize;
        Uint64::new_unchecked(self.0.slice(start..end))
    }
    pub fn status(&self) -> Uint8 {
        let slice = self.as_slice();
        let start = molecule::unpack_number(&slice[28..]) as usize;
        let end = molecule::unpack_number(&slice[32..]) as usize;
        Uint8::new_unchecked(self.0.slice(start..end))
    }
    pub fn records(&self) -> Records {
        let slice = self.as_slice();
        let start = molecule::unpack_number(&slice[32..]) as usize;
        let end = molecule::unpack_number(&slice[36..]) as usize;
        Records::new_unchecked(self.0.slice(start..end))
    }
    pub fn enable_sub_account(&self) -> Uint8 {
        let slice = self.as_slice();
        let start = molecule::unpack_number(&slice[36..]) as usize;
        let end = molecule::unpack_number(&slice[40..]) as usize;
        Uint8::new_unchecked(self.0.slice(start..end))
    }
    pub fn renew_sub_account_price(&self) -> Uint64 {
        let slice = self.as_slice();
        let start = molecule::unpack_number(&slice[40..]) as usize;
        if self.has_extra_fields() {
            let end = molecule::unpack_number(&slice[44..]) as usize;
            Uint64::new_unchecked(self.0.slice(start..end))
        } else {
            Uint64::new_unchecked(self.0.slice(start..))
        }
    }
    pub fn as_reader<'r>(&'r self) -> AccountCellDataV3Reader<'r> {
        AccountCellDataV3Reader::new_unchecked(self.as_slice())
    }
}
impl molecule::prelude::Entity for AccountCellDataV3 {
    type Builder = AccountCellDataV3Builder;
    const NAME: &'static str = "AccountCellDataV3";
    fn new_unchecked(data: molecule::bytes::Bytes) -> Self {
        AccountCellDataV3(data)
    }
    fn as_bytes(&self) -> molecule::bytes::Bytes {
        self.0.clone()
    }
    fn as_slice(&self) -> &[u8] {
        &self.0[..]
    }
    fn from_slice(slice: &[u8]) -> molecule::error::VerificationResult<Self> {
        AccountCellDataV3Reader::from_slice(slice).map(|reader| reader.to_entity())
    }
    fn from_compatible_slice(slice: &[u8]) -> molecule::error::VerificationResult<Self> {
        AccountCellDataV3Reader::from_compatible_slice(slice).map(|reader| reader.to_entity())
    }
    fn new_builder() -> Self::Builder {
        ::core::default::Default::default()
    }
    fn as_builder(self) -> Self::Builder {
        Self::new_builder()
            .id(self.id())
            .account(self.account())
            .registered_at(self.registered_at())
            .last_transfer_account_at(self.last_transfer_account_at())
            .last_edit_manager_at(self.last_edit_manager_at())
            .last_edit_records_at(self.last_edit_records_at())
            .status(self.status())
            .records(self.records())
            .enable_sub_account(self.enable_sub_account())
            .renew_sub_account_price(self.renew_sub_account_price())
    }
}
#[derive(Clone, Copy)]
pub struct AccountCellDataV3Reader<'r>(&'r [u8]);
impl<'r> ::core::fmt::LowerHex for AccountCellDataV3Reader<'r> {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        use molecule::hex_string;
        if f.alternate() {
            write!(f, "0x")?;
        }
        write!(f, "{}", hex_string(self.as_slice()))
    }
}
impl<'r> ::core::fmt::Debug for AccountCellDataV3Reader<'r> {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        write!(f, "{}({:#x})", Self::NAME, self)
    }
}
impl<'r> ::core::fmt::Display for AccountCellDataV3Reader<'r> {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        write!(f, "{} {{ ", Self::NAME)?;
        write!(f, "{}: {}", "id", self.id())?;
        write!(f, ", {}: {}", "account", self.account())?;
        write!(f, ", {}: {}", "registered_at", self.registered_at())?;
        write!(
            f,
            ", {}: {}",
            "last_transfer_account_at",
            self.last_transfer_account_at()
        )?;
        write!(f, ", {}: {}", "last_edit_manager_at", self.last_edit_manager_at())?;
        write!(f, ", {}: {}", "last_edit_records_at", self.last_edit_records_at())?;
        write!(f, ", {}: {}", "status", self.status())?;
        write!(f, ", {}: {}", "records", self.records())?;
        write!(f, ", {}: {}", "enable_sub_account", self.enable_sub_account())?;
        write!(f, ", {}: {}", "renew_sub_account_price", self.renew_sub_account_price())?;
        let extra_count = self.count_extra_fields();
        if extra_count != 0 {
            write!(f, ", .. ({} fields)", extra_count)?;
        }
        write!(f, " }}")
    }
}
impl<'r> AccountCellDataV3Reader<'r> {
    pub const FIELD_COUNT: usize = 10;
    pub fn total_size(&self) -> usize {
        molecule::unpack_number(self.as_slice()) as usize
    }
    pub fn field_count(&self) -> usize {
        if self.total_size() == molecule::NUMBER_SIZE {
            0
        } else {
            (molecule::unpack_number(&self.as_slice()[molecule::NUMBER_SIZE..]) as usize / 4) - 1
        }
    }
    pub fn count_extra_fields(&self) -> usize {
        self.field_count() - Self::FIELD_COUNT
    }
    pub fn has_extra_fields(&self) -> bool {
        Self::FIELD_COUNT != self.field_count()
    }
    pub fn id(&self) -> AccountIdReader<'r> {
        let slice = self.as_slice();
        let start = molecule::unpack_number(&slice[4..]) as usize;
        let end = molecule::unpack_number(&slice[8..]) as usize;
        AccountIdReader::new_unchecked(&self.as_slice()[start..end])
    }
    pub fn account(&self) -> AccountCharsReader<'r> {
        let slice = self.as_slice();
        let start = molecule::unpack_number(&slice[8..]) as usize;
        let end = molecule::unpack_number(&slice[12..]) as usize;
        AccountCharsReader::new_unchecked(&self.as_slice()[start..end])
    }
    pub fn registered_at(&self) -> Uint64Reader<'r> {
        let slice = self.as_slice();
        let start = molecule::unpack_number(&slice[12..]) as usize;
        let end = molecule::unpack_number(&slice[16..]) as usize;
        Uint64Reader::new_unchecked(&self.as_slice()[start..end])
    }
    pub fn last_transfer_account_at(&self) -> Uint64Reader<'r> {
        let slice = self.as_slice();
        let start = molecule::unpack_number(&slice[16..]) as usize;
        let end = molecule::unpack_number(&slice[20..]) as usize;
        Uint64Reader::new_unchecked(&self.as_slice()[start..end])
    }
    pub fn last_edit_manager_at(&self) -> Uint64Reader<'r> {
        let slice = self.as_slice();
        let start = molecule::unpack_number(&slice[20..]) as usize;
        let end = molecule::unpack_number(&slice[24..]) as usize;
        Uint64Reader::new_unchecked(&self.as_slice()[start..end])
    }
    pub fn last_edit_records_at(&self) -> Uint64Reader<'r> {
        let slice = self.as_slice();
        let start = molecule::unpack_number(&slice[24..]) as usize;
        let end = molecule::unpack_number(&slice[28..]) as usize;
        Uint64Reader::new_unchecked(&self.as_slice()[start..end])
    }
    pub fn status(&self) -> Uint8Reader<'r> {
        let slice = self.as_slice();
        let start = molecule::unpack_number(&slice[28..]) as usize;
        let end = molecule::unpack_number(&slice[32..]) as usize;
        Uint8Reader::new_unchecked(&self.as_slice()[start..end])
    }
    pub fn records(&self) -> RecordsReader<'r> {
        let slice = self.as_slice();
        let start = molecule::unpack_number(&slice[32..]) as usize;
        let end = molecule::unpack_number(&slice[36..]) as usize;
        RecordsReader::new_unchecked(&self.as_slice()[start..end])
    }
    pub fn enable_sub_account(&self) -> Uint8Reader<'r> {
        let slice = self.as_slice();
        let start = molecule::unpack_number(&slice[36..]) as usize;
        let end = molecule::unpack_number(&slice[40..]) as usize;
        Uint8Reader::new_unchecked(&self.as_slice()[start..end])
    }
    pub fn renew_sub_account_price(&self) -> Uint64Reader<'r> {
        let slice = self.as_slice();
        let start = molecule::unpack_number(&slice[40..]) as usize;
        if self.has_extra_fields() {
            let end = molecule::unpack_number(&slice[44..]) as usize;
            Uint64Reader::new_unchecked(&self.as_slice()[start..end])
        } else {
            Uint64Reader::new_unchecked(&self.as_slice()[start..])
        }
    }
}
impl<'r> molecule::prelude::Reader<'r> for AccountCellDataV3Reader<'r> {
    type Entity = AccountCellDataV3;
    const NAME: &'static str = "AccountCellDataV3Reader";
    fn to_entity(&self) -> Self::Entity {
        Self::Entity::new_unchecked(self.as_slice().to_owned().into())
    }
    fn new_unchecked(slice: &'r [u8]) -> Self {
        AccountCellDataV3Reader(slice)
    }
    fn as_slice(&self) -> &'r [u8] {
        self.0
    }
    fn verify(slice: &[u8], compatible: bool) -> molecule::error::VerificationResult<()> {
        use molecule::verification_error as ve;
        let slice_len = slice.len();
        if slice_len < molecule::NUMBER_SIZE {
            return ve!(Self, HeaderIsBroken, molecule::NUMBER_SIZE, slice_len);
        }
        let total_size = molecule::unpack_number(slice) as usize;
        if slice_len != total_size {
            return ve!(Self, TotalSizeNotMatch, total_size, slice_len);
        }
        if slice_len == molecule::NUMBER_SIZE && Self::FIELD_COUNT == 0 {
            return Ok(());
        }
        if slice_len < molecule::NUMBER_SIZE * 2 {
            return ve!(Self, HeaderIsBroken, molecule::NUMBER_SIZE * 2, slice_len);
        }
        let offset_first = molecule::unpack_number(&slice[molecule::NUMBER_SIZE..]) as usize;
        if offset_first % molecule::NUMBER_SIZE != 0 || offset_first < molecule::NUMBER_SIZE * 2 {
            return ve!(Self, OffsetsNotMatch);
        }
        if slice_len < offset_first {
            return ve!(Self, HeaderIsBroken, offset_first, slice_len);
        }
        let field_count = offset_first / molecule::NUMBER_SIZE - 1;
        if field_count < Self::FIELD_COUNT {
            return ve!(Self, FieldCountNotMatch, Self::FIELD_COUNT, field_count);
        } else if !compatible && field_count > Self::FIELD_COUNT {
            return ve!(Self, FieldCountNotMatch, Self::FIELD_COUNT, field_count);
        };
        let mut offsets: Vec<usize> = slice[molecule::NUMBER_SIZE..offset_first]
            .chunks_exact(molecule::NUMBER_SIZE)
            .map(|x| molecule::unpack_number(x) as usize)
            .collect();
        offsets.push(total_size);
        if offsets.windows(2).any(|i| i[0] > i[1]) {
            return ve!(Self, OffsetsNotMatch);
        }
        AccountIdReader::verify(&slice[offsets[0]..offsets[1]], compatible)?;
        AccountCharsReader::verify(&slice[offsets[1]..offsets[2]], compatible)?;
        Uint64Reader::verify(&slice[offsets[2]..offsets[3]], compatible)?;
        Uint64Reader::verify(&slice[offsets[3]..offsets[4]], compatible)?;
        Uint64Reader::verify(&slice[offsets[4]..offsets[5]], compatible)?;
        Uint64Reader::verify(&slice[offsets[5]..offsets[6]], compatible)?;
        Uint8Reader::verify(&slice[offsets[6]..offsets[7]], compatible)?;
        RecordsReader::verify(&slice[offsets[7]..offsets[8]], compatible)?;
        Uint8Reader::verify(&slice[offsets[8]..offsets[9]], compatible)?;
        Uint64Reader::verify(&slice[offsets[9]..offsets[10]], compatible)?;
        Ok(())
    }
}
#[derive(Debug, Default)]
pub struct AccountCellDataV3Builder {
    pub(crate) id: AccountId,
    pub(crate) account: AccountChars,
    pub(crate) registered_at: Uint64,
    pub(crate) last_transfer_account_at: Uint64,
    pub(crate) last_edit_manager_at: Uint64,
    pub(crate) last_edit_records_at: Uint64,
    pub(crate) status: Uint8,
    pub(crate) records: Records,
    pub(crate) enable_sub_account: Uint8,
    pub(crate) renew_sub_account_price: Uint64,
}
impl AccountCellDataV3Builder {
    pub const FIELD_COUNT: usize = 10;
    pub fn id(mut self, v: AccountId) -> Self {
        self.id = v;
        self
    }
    pub fn account(mut self, v: AccountChars) -> Self {
        self.account = v;
        self
    }
    pub fn registered_at(mut self, v: Uint64) -> Self {
        self.registered_at = v;
        self
    }
    pub fn last_transfer_account_at(mut self, v: Uint64) -> Self {
        self.last_transfer_account_at = v;
        self
    }
    pub fn last_edit_manager_at(mut self, v: Uint64) -> Self {
        self.last_edit_manager_at = v;
        self
    }
    pub fn last_edit_records_at(mut self, v: Uint64) -> Self {
        self.last_edit_records_at = v;
        self
    }
    pub fn status(mut self, v: Uint8) -> Self {
        self.status = v;
        self
    }
    pub fn records(mut self, v: Records) -> Self {
        self.records = v;
        self
    }
    pub fn enable_sub_account(mut self, v: Uint8) -> Self {
        self.enable_sub_account = v;
        self
    }
    pub fn renew_sub_account_price(mut self, v: Uint64) -> Self {
        self.renew_sub_account_price = v;
        self
    }
}
impl molecule::prelude::Builder for AccountCellDataV3Builder {
    type Entity = AccountCellDataV3;
    const NAME: &'static str = "AccountCellDataV3Builder";
    fn expected_length(&self) -> usize {
        molecule::NUMBER_SIZE * (Self::FIELD_COUNT + 1)
            + self.id.as_slice().len()
            + self.account.as_slice().len()
            + self.registered_at.as_slice().len()
            + self.last_transfer_account_at.as_slice().len()
            + self.last_edit_manager_at.as_slice().len()
            + self.last_edit_records_at.as_slice().len()
            + self.status.as_slice().len()
            + self.records.as_slice().len()
            + self.enable_sub_account.as_slice().len()
            + self.renew_sub_account_price.as_slice().len()
    }
    fn write<W: molecule::io::Write>(&self, writer: &mut W) -> molecule::io::Result<()> {
        let mut total_size = molecule::NUMBER_SIZE * (Self::FIELD_COUNT + 1);
        let mut offsets = Vec::with_capacity(Self::FIELD_COUNT);
        offsets.push(total_size);
        total_size += self.id.as_slice().len();
        offsets.push(total_size);
        total_size += self.account.as_slice().len();
        offsets.push(total_size);
        total_size += self.registered_at.as_slice().len();
        offsets.push(total_size);
        total_size += self.last_transfer_account_at.as_slice().len();
        offsets.push(total_size);
        total_size += self.last_edit_manager_at.as_slice().len();
        offsets.push(total_size);
        total_size += self.last_edit_records_at.as_slice().len();
        offsets.push(total_size);
        total_size += self.status.as_slice().len();
        offsets.push(total_size);
        total_size += self.records.as_slice().len();
        offsets.push(total_size);
        total_size += self.enable_sub_account.as_slice().len();
        offsets.push(total_size);
        total_size += self.renew_sub_account_price.as_slice().len();
        writer.write_all(&molecule::pack_number(total_size as molecule::Number))?;
        for offset in offsets.into_iter() {
            writer.write_all(&molecule::pack_number(offset as molecule::Number))?;
        }
        writer.write_all(self.id.as_slice())?;
        writer.write_all(self.account.as_slice())?;
        writer.write_all(self.registered_at.as_slice())?;
        writer.write_all(self.last_transfer_account_at.as_slice())?;
        writer.write_all(self.last_edit_manager_at.as_slice())?;
        writer.write_all(self.last_edit_records_at.as_slice())?;
        writer.write_all(self.status.as_slice())?;
        writer.write_all(self.records.as_slice())?;
        writer.write_all(self.enable_sub_account.as_slice())?;
        writer.write_all(self.renew_sub_account_price.as_slice())?;
        Ok(())
    }
    fn build(&self) -> Self::Entity {
        let mut inner = Vec::with_capacity(self.expected_length());
        self.write(&mut inner)
            .unwrap_or_else(|_| panic!("{} build should be ok", Self::NAME));
        AccountCellDataV3::new_unchecked(inner.into())
    }
}
