// Generated by Molecule 0.7.5
// Generated by Moleculec-Go 0.1.11

package cell_v2
import (
    "bytes"
    "encoding/binary"
    "errors"
    "strconv"
    "strings"
       )

type AccountCellDataV2Builder struct {
    id AccountId
account AccountChars
registered_at Uint64
last_transfer_account_at Uint64
last_edit_manager_at Uint64
last_edit_records_at Uint64
status Uint8
records Records
}
        

func (s *AccountCellDataV2Builder) Build() AccountCellDataV2 {
    b := new(bytes.Buffer)

    totalSize := HeaderSizeUint * (8 + 1)
    offsets := make([]uint32, 0, 8)

    offsets = append(offsets, totalSize)
totalSize += uint32(len(s.id.AsSlice()))
offsets = append(offsets, totalSize)
totalSize += uint32(len(s.account.AsSlice()))
offsets = append(offsets, totalSize)
totalSize += uint32(len(s.registered_at.AsSlice()))
offsets = append(offsets, totalSize)
totalSize += uint32(len(s.last_transfer_account_at.AsSlice()))
offsets = append(offsets, totalSize)
totalSize += uint32(len(s.last_edit_manager_at.AsSlice()))
offsets = append(offsets, totalSize)
totalSize += uint32(len(s.last_edit_records_at.AsSlice()))
offsets = append(offsets, totalSize)
totalSize += uint32(len(s.status.AsSlice()))
offsets = append(offsets, totalSize)
totalSize += uint32(len(s.records.AsSlice()))

    b.Write(packNumber(Number(totalSize)))

    for i := 0; i < len(offsets); i++ {
        b.Write(packNumber(Number(offsets[i])))
    }

    b.Write(s.id.AsSlice())
b.Write(s.account.AsSlice())
b.Write(s.registered_at.AsSlice())
b.Write(s.last_transfer_account_at.AsSlice())
b.Write(s.last_edit_manager_at.AsSlice())
b.Write(s.last_edit_records_at.AsSlice())
b.Write(s.status.AsSlice())
b.Write(s.records.AsSlice())
    return AccountCellDataV2{inner: b.Bytes()}
}
                

func (s *AccountCellDataV2Builder) Id(v AccountId) *AccountCellDataV2Builder {
    s.id = v
    return s
}
            

func (s *AccountCellDataV2Builder) Account(v AccountChars) *AccountCellDataV2Builder {
    s.account = v
    return s
}
            

func (s *AccountCellDataV2Builder) RegisteredAt(v Uint64) *AccountCellDataV2Builder {
    s.registered_at = v
    return s
}
            

func (s *AccountCellDataV2Builder) LastTransferAccountAt(v Uint64) *AccountCellDataV2Builder {
    s.last_transfer_account_at = v
    return s
}
            

func (s *AccountCellDataV2Builder) LastEditManagerAt(v Uint64) *AccountCellDataV2Builder {
    s.last_edit_manager_at = v
    return s
}
            

func (s *AccountCellDataV2Builder) LastEditRecordsAt(v Uint64) *AccountCellDataV2Builder {
    s.last_edit_records_at = v
    return s
}
            

func (s *AccountCellDataV2Builder) Status(v Uint8) *AccountCellDataV2Builder {
    s.status = v
    return s
}
            

func (s *AccountCellDataV2Builder) Records(v Records) *AccountCellDataV2Builder {
    s.records = v
    return s
}
            

func NewAccountCellDataV2Builder() *AccountCellDataV2Builder {
	return &AccountCellDataV2Builder{ id: AccountIdDefault(),account: AccountCharsDefault(),registered_at: Uint64Default(),last_transfer_account_at: Uint64Default(),last_edit_manager_at: Uint64Default(),last_edit_records_at: Uint64Default(),status: Uint8Default(),records: RecordsDefault() }
}
    

type AccountCellDataV2 struct {
    inner []byte
}
        

func AccountCellDataV2FromSliceUnchecked(slice []byte) *AccountCellDataV2 {
    return &AccountCellDataV2{inner: slice}
}
func (s *AccountCellDataV2) AsSlice() []byte {
    return s.inner
}
            

func AccountCellDataV2Default() AccountCellDataV2 {
    return *AccountCellDataV2FromSliceUnchecked([]byte{ 97,0,0,0,36,0,0,0,56,0,0,0,60,0,0,0,68,0,0,0,76,0,0,0,84,0,0,0,92,0,0,0,93,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4,0,0,0 })
}
            

func AccountCellDataV2FromSlice(slice []byte, compatible bool) (*AccountCellDataV2, error) {
    sliceLen := len(slice)
    if uint32(sliceLen) < HeaderSizeUint {
        errMsg := strings.Join([]string{"HeaderIsBroken", "AccountCellDataV2", strconv.Itoa(int(sliceLen)), "<", strconv.Itoa(int(HeaderSizeUint))}, " ")
        return nil, errors.New(errMsg)
    }

    totalSize := unpackNumber(slice)
    if Number(sliceLen) != totalSize {
        errMsg := strings.Join([]string{"TotalSizeNotMatch", "AccountCellDataV2", strconv.Itoa(int(sliceLen)), "!=", strconv.Itoa(int(totalSize))}, " ")
        return nil, errors.New(errMsg)
    }

    if uint32(sliceLen) < HeaderSizeUint*2 {
        errMsg := strings.Join([]string{"TotalSizeNotMatch", "AccountCellDataV2", strconv.Itoa(int(sliceLen)), "<", strconv.Itoa(int(HeaderSizeUint*2))}, " ")
        return nil, errors.New(errMsg)
    }

    offsetFirst := unpackNumber(slice[HeaderSizeUint:])
    if uint32(offsetFirst)%HeaderSizeUint != 0 || uint32(offsetFirst) < HeaderSizeUint*2 {
        errMsg := strings.Join([]string{"OffsetsNotMatch", "AccountCellDataV2", strconv.Itoa(int(offsetFirst%4)), "!= 0", strconv.Itoa(int(offsetFirst)), "<", strconv.Itoa(int(HeaderSizeUint*2))}, " ")
        return nil, errors.New(errMsg)
    }

    if sliceLen < int(offsetFirst) {
        errMsg := strings.Join([]string{"HeaderIsBroken", "AccountCellDataV2", strconv.Itoa(int(sliceLen)), "<", strconv.Itoa(int(offsetFirst))}, " ")
        return nil, errors.New(errMsg)
    }

    fieldCount := uint32(offsetFirst)/HeaderSizeUint - 1
    if fieldCount < 8 {
        return nil, errors.New("FieldCountNotMatch")
    } else if !compatible && fieldCount > 8 {
        return nil, errors.New("FieldCountNotMatch")
    }

    offsets := make([]uint32, fieldCount)

    for i := 0; i < int(fieldCount); i++ {
        offsets[i] = uint32(unpackNumber(slice[HeaderSizeUint:][int(HeaderSizeUint)*i:]))
    }
    offsets = append(offsets, uint32(totalSize))

    for i := 0; i < len(offsets); i++ {
        if i&1 != 0 && offsets[i-1] > offsets[i] {
            return nil, errors.New("OffsetsNotMatch")
        }
    }

    var err error
    
_, err = AccountIdFromSlice(slice[offsets[0]:offsets[1]], compatible)
if err != nil {
    return nil, err
}
                

_, err = AccountCharsFromSlice(slice[offsets[1]:offsets[2]], compatible)
if err != nil {
    return nil, err
}
                

_, err = Uint64FromSlice(slice[offsets[2]:offsets[3]], compatible)
if err != nil {
    return nil, err
}
                

_, err = Uint64FromSlice(slice[offsets[3]:offsets[4]], compatible)
if err != nil {
    return nil, err
}
                

_, err = Uint64FromSlice(slice[offsets[4]:offsets[5]], compatible)
if err != nil {
    return nil, err
}
                

_, err = Uint64FromSlice(slice[offsets[5]:offsets[6]], compatible)
if err != nil {
    return nil, err
}
                

_, err = Uint8FromSlice(slice[offsets[6]:offsets[7]], compatible)
if err != nil {
    return nil, err
}
                

_, err = RecordsFromSlice(slice[offsets[7]:offsets[8]], compatible)
if err != nil {
    return nil, err
}
                

    return &AccountCellDataV2{inner: slice}, nil
}
            

func (s *AccountCellDataV2) TotalSize() uint {
    return uint(unpackNumber(s.inner))
}
func (s *AccountCellDataV2) FieldCount() uint {
    var number uint = 0
    if uint32(s.TotalSize()) == HeaderSizeUint {
        return number
    }
    number = uint(unpackNumber(s.inner[HeaderSizeUint:]))/4 - 1
    return number
}
func (s *AccountCellDataV2) Len() uint {
    return s.FieldCount()
}
func (s *AccountCellDataV2) IsEmpty() bool {
    return s.Len() == 0
}
func (s *AccountCellDataV2) CountExtraFields() uint {
    return s.FieldCount() - 8
}

func (s *AccountCellDataV2) HasExtraFields() bool {
    return 8 != s.FieldCount()
}
            

func (s *AccountCellDataV2) Id() *AccountId {
    start := unpackNumber(s.inner[4:])
    end := unpackNumber(s.inner[8:])
    return AccountIdFromSliceUnchecked(s.inner[start:end])
}
               

func (s *AccountCellDataV2) Account() *AccountChars {
    start := unpackNumber(s.inner[8:])
    end := unpackNumber(s.inner[12:])
    return AccountCharsFromSliceUnchecked(s.inner[start:end])
}
               

func (s *AccountCellDataV2) RegisteredAt() *Uint64 {
    start := unpackNumber(s.inner[12:])
    end := unpackNumber(s.inner[16:])
    return Uint64FromSliceUnchecked(s.inner[start:end])
}
               

func (s *AccountCellDataV2) LastTransferAccountAt() *Uint64 {
    start := unpackNumber(s.inner[16:])
    end := unpackNumber(s.inner[20:])
    return Uint64FromSliceUnchecked(s.inner[start:end])
}
               

func (s *AccountCellDataV2) LastEditManagerAt() *Uint64 {
    start := unpackNumber(s.inner[20:])
    end := unpackNumber(s.inner[24:])
    return Uint64FromSliceUnchecked(s.inner[start:end])
}
               

func (s *AccountCellDataV2) LastEditRecordsAt() *Uint64 {
    start := unpackNumber(s.inner[24:])
    end := unpackNumber(s.inner[28:])
    return Uint64FromSliceUnchecked(s.inner[start:end])
}
               

func (s *AccountCellDataV2) Status() *Uint8 {
    start := unpackNumber(s.inner[28:])
    end := unpackNumber(s.inner[32:])
    return Uint8FromSliceUnchecked(s.inner[start:end])
}
               

func (s *AccountCellDataV2) Records() *Records {
    var ret *Records
    start := unpackNumber(s.inner[32:])
    if s.HasExtraFields() {
        end := unpackNumber(s.inner[36:])
        ret = RecordsFromSliceUnchecked(s.inner[start:end])
    } else {
        ret = RecordsFromSliceUnchecked(s.inner[start:])
    }
    return ret
}
                        

func (s *AccountCellDataV2) AsBuilder() AccountCellDataV2Builder {
    ret := NewAccountCellDataV2Builder().Id(*s.Id()).Account(*s.Account()).RegisteredAt(*s.RegisteredAt()).LastTransferAccountAt(*s.LastTransferAccountAt()).LastEditManagerAt(*s.LastEditManagerAt()).LastEditRecordsAt(*s.LastEditRecordsAt()).Status(*s.Status()).Records(*s.Records())
    return *ret
}
        

type PreAccountCellDataV2Builder struct {
    account AccountChars
refund_lock Script
owner_lock_args Bytes
inviter_id Bytes
inviter_lock ScriptOpt
channel_lock ScriptOpt
price PriceConfig
quote Uint64
invited_discount Uint32
created_at Uint64
initial_records Records
}
        

func (s *PreAccountCellDataV2Builder) Build() PreAccountCellDataV2 {
    b := new(bytes.Buffer)

    totalSize := HeaderSizeUint * (11 + 1)
    offsets := make([]uint32, 0, 11)

    offsets = append(offsets, totalSize)
totalSize += uint32(len(s.account.AsSlice()))
offsets = append(offsets, totalSize)
totalSize += uint32(len(s.refund_lock.AsSlice()))
offsets = append(offsets, totalSize)
totalSize += uint32(len(s.owner_lock_args.AsSlice()))
offsets = append(offsets, totalSize)
totalSize += uint32(len(s.inviter_id.AsSlice()))
offsets = append(offsets, totalSize)
totalSize += uint32(len(s.inviter_lock.AsSlice()))
offsets = append(offsets, totalSize)
totalSize += uint32(len(s.channel_lock.AsSlice()))
offsets = append(offsets, totalSize)
totalSize += uint32(len(s.price.AsSlice()))
offsets = append(offsets, totalSize)
totalSize += uint32(len(s.quote.AsSlice()))
offsets = append(offsets, totalSize)
totalSize += uint32(len(s.invited_discount.AsSlice()))
offsets = append(offsets, totalSize)
totalSize += uint32(len(s.created_at.AsSlice()))
offsets = append(offsets, totalSize)
totalSize += uint32(len(s.initial_records.AsSlice()))

    b.Write(packNumber(Number(totalSize)))

    for i := 0; i < len(offsets); i++ {
        b.Write(packNumber(Number(offsets[i])))
    }

    b.Write(s.account.AsSlice())
b.Write(s.refund_lock.AsSlice())
b.Write(s.owner_lock_args.AsSlice())
b.Write(s.inviter_id.AsSlice())
b.Write(s.inviter_lock.AsSlice())
b.Write(s.channel_lock.AsSlice())
b.Write(s.price.AsSlice())
b.Write(s.quote.AsSlice())
b.Write(s.invited_discount.AsSlice())
b.Write(s.created_at.AsSlice())
b.Write(s.initial_records.AsSlice())
    return PreAccountCellDataV2{inner: b.Bytes()}
}
                

func (s *PreAccountCellDataV2Builder) Account(v AccountChars) *PreAccountCellDataV2Builder {
    s.account = v
    return s
}
            

func (s *PreAccountCellDataV2Builder) RefundLock(v Script) *PreAccountCellDataV2Builder {
    s.refund_lock = v
    return s
}
            

func (s *PreAccountCellDataV2Builder) OwnerLockArgs(v Bytes) *PreAccountCellDataV2Builder {
    s.owner_lock_args = v
    return s
}
            

func (s *PreAccountCellDataV2Builder) InviterId(v Bytes) *PreAccountCellDataV2Builder {
    s.inviter_id = v
    return s
}
            

func (s *PreAccountCellDataV2Builder) InviterLock(v ScriptOpt) *PreAccountCellDataV2Builder {
    s.inviter_lock = v
    return s
}
            

func (s *PreAccountCellDataV2Builder) ChannelLock(v ScriptOpt) *PreAccountCellDataV2Builder {
    s.channel_lock = v
    return s
}
            

func (s *PreAccountCellDataV2Builder) Price(v PriceConfig) *PreAccountCellDataV2Builder {
    s.price = v
    return s
}
            

func (s *PreAccountCellDataV2Builder) Quote(v Uint64) *PreAccountCellDataV2Builder {
    s.quote = v
    return s
}
            

func (s *PreAccountCellDataV2Builder) InvitedDiscount(v Uint32) *PreAccountCellDataV2Builder {
    s.invited_discount = v
    return s
}
            

func (s *PreAccountCellDataV2Builder) CreatedAt(v Uint64) *PreAccountCellDataV2Builder {
    s.created_at = v
    return s
}
            

func (s *PreAccountCellDataV2Builder) InitialRecords(v Records) *PreAccountCellDataV2Builder {
    s.initial_records = v
    return s
}
            

func NewPreAccountCellDataV2Builder() *PreAccountCellDataV2Builder {
	return &PreAccountCellDataV2Builder{ account: AccountCharsDefault(),refund_lock: ScriptDefault(),owner_lock_args: BytesDefault(),inviter_id: BytesDefault(),inviter_lock: ScriptOptDefault(),channel_lock: ScriptOptDefault(),price: PriceConfigDefault(),quote: Uint64Default(),invited_discount: Uint32Default(),created_at: Uint64Default(),initial_records: RecordsDefault() }
}
    

type PreAccountCellDataV2 struct {
    inner []byte
}
        

func PreAccountCellDataV2FromSliceUnchecked(slice []byte) *PreAccountCellDataV2 {
    return &PreAccountCellDataV2{inner: slice}
}
func (s *PreAccountCellDataV2) AsSlice() []byte {
    return s.inner
}
            

func PreAccountCellDataV2Default() PreAccountCellDataV2 {
    return *PreAccountCellDataV2FromSliceUnchecked([]byte{ 170,0,0,0,48,0,0,0,52,0,0,0,105,0,0,0,109,0,0,0,113,0,0,0,113,0,0,0,113,0,0,0,146,0,0,0,154,0,0,0,158,0,0,0,166,0,0,0,4,0,0,0,53,0,0,0,16,0,0,0,48,0,0,0,49,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,33,0,0,0,16,0,0,0,17,0,0,0,25,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4,0,0,0 })
}
            

func PreAccountCellDataV2FromSlice(slice []byte, compatible bool) (*PreAccountCellDataV2, error) {
    sliceLen := len(slice)
    if uint32(sliceLen) < HeaderSizeUint {
        errMsg := strings.Join([]string{"HeaderIsBroken", "PreAccountCellDataV2", strconv.Itoa(int(sliceLen)), "<", strconv.Itoa(int(HeaderSizeUint))}, " ")
        return nil, errors.New(errMsg)
    }

    totalSize := unpackNumber(slice)
    if Number(sliceLen) != totalSize {
        errMsg := strings.Join([]string{"TotalSizeNotMatch", "PreAccountCellDataV2", strconv.Itoa(int(sliceLen)), "!=", strconv.Itoa(int(totalSize))}, " ")
        return nil, errors.New(errMsg)
    }

    if uint32(sliceLen) < HeaderSizeUint*2 {
        errMsg := strings.Join([]string{"TotalSizeNotMatch", "PreAccountCellDataV2", strconv.Itoa(int(sliceLen)), "<", strconv.Itoa(int(HeaderSizeUint*2))}, " ")
        return nil, errors.New(errMsg)
    }

    offsetFirst := unpackNumber(slice[HeaderSizeUint:])
    if uint32(offsetFirst)%HeaderSizeUint != 0 || uint32(offsetFirst) < HeaderSizeUint*2 {
        errMsg := strings.Join([]string{"OffsetsNotMatch", "PreAccountCellDataV2", strconv.Itoa(int(offsetFirst%4)), "!= 0", strconv.Itoa(int(offsetFirst)), "<", strconv.Itoa(int(HeaderSizeUint*2))}, " ")
        return nil, errors.New(errMsg)
    }

    if sliceLen < int(offsetFirst) {
        errMsg := strings.Join([]string{"HeaderIsBroken", "PreAccountCellDataV2", strconv.Itoa(int(sliceLen)), "<", strconv.Itoa(int(offsetFirst))}, " ")
        return nil, errors.New(errMsg)
    }

    fieldCount := uint32(offsetFirst)/HeaderSizeUint - 1
    if fieldCount < 11 {
        return nil, errors.New("FieldCountNotMatch")
    } else if !compatible && fieldCount > 11 {
        return nil, errors.New("FieldCountNotMatch")
    }

    offsets := make([]uint32, fieldCount)

    for i := 0; i < int(fieldCount); i++ {
        offsets[i] = uint32(unpackNumber(slice[HeaderSizeUint:][int(HeaderSizeUint)*i:]))
    }
    offsets = append(offsets, uint32(totalSize))

    for i := 0; i < len(offsets); i++ {
        if i&1 != 0 && offsets[i-1] > offsets[i] {
            return nil, errors.New("OffsetsNotMatch")
        }
    }

    var err error
    
_, err = AccountCharsFromSlice(slice[offsets[0]:offsets[1]], compatible)
if err != nil {
    return nil, err
}
                

_, err = ScriptFromSlice(slice[offsets[1]:offsets[2]], compatible)
if err != nil {
    return nil, err
}
                

_, err = BytesFromSlice(slice[offsets[2]:offsets[3]], compatible)
if err != nil {
    return nil, err
}
                

_, err = BytesFromSlice(slice[offsets[3]:offsets[4]], compatible)
if err != nil {
    return nil, err
}
                

_, err = ScriptOptFromSlice(slice[offsets[4]:offsets[5]], compatible)
if err != nil {
    return nil, err
}
                

_, err = ScriptOptFromSlice(slice[offsets[5]:offsets[6]], compatible)
if err != nil {
    return nil, err
}
                

_, err = PriceConfigFromSlice(slice[offsets[6]:offsets[7]], compatible)
if err != nil {
    return nil, err
}
                

_, err = Uint64FromSlice(slice[offsets[7]:offsets[8]], compatible)
if err != nil {
    return nil, err
}
                

_, err = Uint32FromSlice(slice[offsets[8]:offsets[9]], compatible)
if err != nil {
    return nil, err
}
                

_, err = Uint64FromSlice(slice[offsets[9]:offsets[10]], compatible)
if err != nil {
    return nil, err
}
                

_, err = RecordsFromSlice(slice[offsets[10]:offsets[11]], compatible)
if err != nil {
    return nil, err
}
                

    return &PreAccountCellDataV2{inner: slice}, nil
}
            

func (s *PreAccountCellDataV2) TotalSize() uint {
    return uint(unpackNumber(s.inner))
}
func (s *PreAccountCellDataV2) FieldCount() uint {
    var number uint = 0
    if uint32(s.TotalSize()) == HeaderSizeUint {
        return number
    }
    number = uint(unpackNumber(s.inner[HeaderSizeUint:]))/4 - 1
    return number
}
func (s *PreAccountCellDataV2) Len() uint {
    return s.FieldCount()
}
func (s *PreAccountCellDataV2) IsEmpty() bool {
    return s.Len() == 0
}
func (s *PreAccountCellDataV2) CountExtraFields() uint {
    return s.FieldCount() - 11
}

func (s *PreAccountCellDataV2) HasExtraFields() bool {
    return 11 != s.FieldCount()
}
            

func (s *PreAccountCellDataV2) Account() *AccountChars {
    start := unpackNumber(s.inner[4:])
    end := unpackNumber(s.inner[8:])
    return AccountCharsFromSliceUnchecked(s.inner[start:end])
}
               

func (s *PreAccountCellDataV2) RefundLock() *Script {
    start := unpackNumber(s.inner[8:])
    end := unpackNumber(s.inner[12:])
    return ScriptFromSliceUnchecked(s.inner[start:end])
}
               

func (s *PreAccountCellDataV2) OwnerLockArgs() *Bytes {
    start := unpackNumber(s.inner[12:])
    end := unpackNumber(s.inner[16:])
    return BytesFromSliceUnchecked(s.inner[start:end])
}
               

func (s *PreAccountCellDataV2) InviterId() *Bytes {
    start := unpackNumber(s.inner[16:])
    end := unpackNumber(s.inner[20:])
    return BytesFromSliceUnchecked(s.inner[start:end])
}
               

func (s *PreAccountCellDataV2) InviterLock() *ScriptOpt {
    start := unpackNumber(s.inner[20:])
    end := unpackNumber(s.inner[24:])
    return ScriptOptFromSliceUnchecked(s.inner[start:end])
}
               

func (s *PreAccountCellDataV2) ChannelLock() *ScriptOpt {
    start := unpackNumber(s.inner[24:])
    end := unpackNumber(s.inner[28:])
    return ScriptOptFromSliceUnchecked(s.inner[start:end])
}
               

func (s *PreAccountCellDataV2) Price() *PriceConfig {
    start := unpackNumber(s.inner[28:])
    end := unpackNumber(s.inner[32:])
    return PriceConfigFromSliceUnchecked(s.inner[start:end])
}
               

func (s *PreAccountCellDataV2) Quote() *Uint64 {
    start := unpackNumber(s.inner[32:])
    end := unpackNumber(s.inner[36:])
    return Uint64FromSliceUnchecked(s.inner[start:end])
}
               

func (s *PreAccountCellDataV2) InvitedDiscount() *Uint32 {
    start := unpackNumber(s.inner[36:])
    end := unpackNumber(s.inner[40:])
    return Uint32FromSliceUnchecked(s.inner[start:end])
}
               

func (s *PreAccountCellDataV2) CreatedAt() *Uint64 {
    start := unpackNumber(s.inner[40:])
    end := unpackNumber(s.inner[44:])
    return Uint64FromSliceUnchecked(s.inner[start:end])
}
               

func (s *PreAccountCellDataV2) InitialRecords() *Records {
    var ret *Records
    start := unpackNumber(s.inner[44:])
    if s.HasExtraFields() {
        end := unpackNumber(s.inner[48:])
        ret = RecordsFromSliceUnchecked(s.inner[start:end])
    } else {
        ret = RecordsFromSliceUnchecked(s.inner[start:])
    }
    return ret
}
                        

func (s *PreAccountCellDataV2) AsBuilder() PreAccountCellDataV2Builder {
    ret := NewPreAccountCellDataV2Builder().Account(*s.Account()).RefundLock(*s.RefundLock()).OwnerLockArgs(*s.OwnerLockArgs()).InviterId(*s.InviterId()).InviterLock(*s.InviterLock()).ChannelLock(*s.ChannelLock()).Price(*s.Price()).Quote(*s.Quote()).InvitedDiscount(*s.InvitedDiscount()).CreatedAt(*s.CreatedAt()).InitialRecords(*s.InitialRecords())
    return *ret
}
        
